#!/usr/bin/env bash
# Generated by gpt

NUM_RUNS=100
winsAI1=0
winsAI2=0
ties=0

for i in $(seq 1 $NUM_RUNS)
do
    # Run the game once and capture all output in a variable
    OUTPUT=$(python3 main.py 7 7 2 l ../checkers-cpp/main main.py)

    # Check which player won (or if it was a tie)
    if echo "$OUTPUT" | grep -q "player 1 wins"; then
        winsAI1=$((winsAI1+1))
    elif echo "$OUTPUT" | grep -q "player 2 wins"; then
        winsAI2=$((winsAI2+1))
    elif echo "$OUTPUT" | grep -q "Tie"; then
        ties=$((ties+1))
    fi

    echo "Round $i finished P1: $winsAI1 P2: $winsAI2 Ties: $ties"
done

echo "-------------------------------------"
echo "After $NUM_RUNS runs:"
echo "Player 1 (../checkers-cpp/main) wins: $winsAI1"
echo "Player 2 (main.py) wins: $winsAI2"
echo "Ties: $ties"
